stages:
  - clean
  - build
  - deploy

clean-job:
  stage: clean
  script:
     #Config-server
    - echo "Stopping application process..."
    - if [ -f app.pid ]; then kill -9 $(cat app.pid); fi
    - echo "Terminating any process on port 10000..."
    - if lsof -i:10000; then kill -9 $(lsof -ti:10000); fi
    
      #Discovery-service
    - echo "Stopping application process..."
    - if [ -f app.pid ]; then kill -9 $(cat app.pid); fi
    - echo "Terminating any process on port 8668..."
    - if lsof -i:8668; then kill -9 $(lsof -ti:8668); fi

      #Gateway
    - echo "Stopping application process..."
    - if [ -f app.pid ]; then kill -9 $(cat app.pid); fi
    - echo "Terminating any process on port 4444..."
    - if lsof -i:4444; then kill -9 $(lsof -ti:4444); fi

      #Order
    - echo "Stopping application process..."
    - if [ -f app.pid ]; then kill -9 $(cat app.pid); fi
    - echo "Terminating any process on port 5656..."
    - if lsof -i:5656; then kill -9 $(lsof -ti:5656); fi

      #Pi
    - echo "Stopping application process..."
    - if [ -f app.pid ]; then kill -9 $(cat app.pid); fi
    - echo "Terminating any process on port 3434..."
    - if lsof -i:3434; then kill -9 $(lsof -ti:3434); fi

      #Product
    - echo "Stopping application process..."
    - if [ -f app.pid ]; then kill -9 $(cat app.pid); fi
    - echo "Terminating any process on port 2323..."
    - if lsof -i:2323; then kill -9 $(lsof -ti:2323); fi

      #Production
    - echo "Stopping application process..."
    - if [ -f app.pid ]; then kill -9 $(cat app.pid); fi
    - echo "Terminating any process on port 6767..."
    - if lsof -i:6767; then kill -9 $(lsof -ti:6767); fi
  tags:
    - GPRO-RUNNER

build-job:
  stage: build
  script:
    - mkdir -p artifacts
    - echo "Compiling the config server code..."
    - cd gpao-tex-core/config-server && mvn package -DskipTests
    - echo "Compile complete."
    - mv target/config-server-1.0.0.jar ../../../artifacts/

    - echo "Compiling the discovery service code..."
    - cd ../discovery && mvn package -DskipTests
    - echo "Compile complete."
    - mv target/discovery-1.0.0.jar ../../../artifacts/

    - echo "Compiling the gateway service code..."
    - cd ../gateway && mvn package -DskipTests
    - echo "Compile complete."
    - mv target/gateway-1.0.0.jar ../../../artifacts/

    - echo "Compiling the partie-prenante service code..."
    - cd ../partie-prenante && mvn package -DskipTests
    - echo "Compile complete."
    - mv target/partie-prenante-1.0.0.jar ../../../artifacts/

    - echo "Compiling the produit service code..."
    - cd ../produit && mvn package -DskipTests
    - echo "Compile complete."
    - mv target/produit-1.0.0.jar ../../../artifacts/

    - echo "Compiling the ordre service code..."
    - cd ../ordre && mvn package -DskipTests
    - echo "Compile complete."
    - mv target/ordre-1.0.0.jar ../../../artifacts/

    - echo "Compiling the production service code..."
    - cd ../production && mvn package -DskipTests
    - echo "Compile complete."
    - mv target/production-1.0.0.jar ../../../artifacts/
  tags:
    - GPRO-RUNNER

deploy-config-server-job:
  stage: deploy
  script:
    - cd artifacts
    - echo "Deploying the config server code...."
    - nohup java -jar config-server-1.0.0.jar > config-server.log 2>&1 & 
    - sleep 30
    - echo "Checking application health..."
    - curl -f http://localhost:10000/actuator/health || (echo "Application failed to start" && cat config-server.log && exit 1)
  needs:
    - build-job
  variables:
    GIT_STRATEGY: none
  tags:
    - GPRO-RUNNER

deploy-discovery-job:
  stage: deploy
  script:
    - cd artifacts
    - echo "Deploying the discovery service code...."
    - nohup java -jar discovery-1.0.0.jar > discovery.log 2>&1 & 
    - sleep 30
    - echo "Checking application health..."
    - curl -f http://localhost:8668/actuator/health || (echo "Application failed to start" && cat discovery.log && exit 1)
  needs:
    - build-job
  variables:
    GIT_STRATEGY: none
  tags:
    - GPRO-RUNNER

# Add similar deploy jobs for other services as needed
