server:
  port: 6767

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: DEBUG
    io.micrometer: TRACE
jwt:
  auth:
    converter:
      resource-id: gpao-client
      principle-attribute: preferred_username
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/gpao-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://188.40.173.211:5454/production
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    chaine-url: http://localhost:4444/api/order/chaine
    couleur-url: http://localhost:4444/api/produit/couleur
    details-of-url: http://localhost:4444/api/ordre/detailsOf
    of-url: http://localhost:4444/api/ordre/of
    pd-url: http://localhost:4444/api/produit/pd
    taille-url: http://localhost:4444/api/produit/taille
    site-url: http://localhost:4444/api/produit/site


