#spring:
#  config:
#    import: optional:configserver:http://localhost:10000
#  application:
#    name: discovery-server

spring:
  application:
    name: discovery-service
  cloud:
    config:
      enabled: false
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
server:
  port: 8668