#name: Build & Deploy Microservices App
#
#on:
#  push:
#    branches:
#      - main
#jobs:
#  build-deploy:
#    name: Build & Deploy Spring boot Microservice App
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Setup JDK 17
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'corretto'
#          java-version: 17
#
#      - name: Test & Build All Services
#        run: |
#          for service in config-server discovery gateway ordre partie-prenante produit production; do
#            echo "Building $service"
#            mvn -B test --file ./gpao-tex-core/$service/pom.xml
#            mvn clean package -DskipTests --file ./gpao-tex-core/$service/pom.xml
#          done
#
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}
#
#
#      - name: Build Docker images
#        run: |
#          docker build -t ${{ secrets.DOCKER_USERNAME }}/gpro-config-service:latest ./gpao-tex-core/config-server
#          docker build -t ${{ secrets.DOCKER_USERNAME }}/gpro-discovery-service:latest ./gpao-tex-core/discovery
#          docker build -t ${{ secrets.DOCKER_USERNAME }}/gpro-gateway-service:latest ./gpao-tex-core/gateway          
#          docker build -t ${{ secrets.DOCKER_USERNAME }}/gpro-ordre-service:latest ./gpao-tex-core/ordre
#          docker build -t ${{ secrets.DOCKER_USERNAME }}/gpro-produit-service:latest ./gpao-tex-core/produit
#          docker build -t ${{ secrets.DOCKER_USERNAME }}/gpro-production-service:latest ./gpao-tex-core/production
#          docker build -t ${{ secrets.DOCKER_USERNAME }}/gpro-partie-prenante-service:latest ./gpao-tex-core/partie-prenante
#
#      - name: Push Docker images
#        run: |
#          docker push ${{ secrets.DOCKER_USERNAME }}/gpro-config-service:latest
#          docker push ${{ secrets.DOCKER_USERNAME }}/gpro-discovery-service:latest
#          docker push ${{ secrets.DOCKER_USERNAME }}/gpro-gateway-service:latest
#          docker push ${{ secrets.DOCKER_USERNAME }}/gpro-ordre-service:latest
#          docker push ${{ secrets.DOCKER_USERNAME }}/gpro-produit-service:latest
#          docker push ${{ secrets.DOCKER_USERNAME }}/gpro-production-service:latest
#          docker push ${{ secrets.DOCKER_USERNAME }}/gpro-partie-prenante-service:latest
#



name: Build & Deploy Microservices App

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build & Deploy Spring boot Microservice App
    runs-on: ubuntu-latest
    env:
      SERVICES: "config-server discovery gateway ordre partie-prenante produit production"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Determine changed directories
        id: changes
        run: |
          echo "##[group]Detecting changes"
          CHANGED_SERVICES=""
          for service in $SERVICES; do
            if git diff --name-only HEAD^ HEAD | grep -q "^gpao-tex-core/$service/"; then
              echo "$service has changed"
              CHANGED_SERVICES="$CHANGED_SERVICES $service"
            fi
          done
          echo "CHANGED_SERVICES=$CHANGED_SERVICES" >> $GITHUB_ENV
          echo "##[endgroup]"

      - name: Test & Build Changed Services
        run: |
          if [ -z "$CHANGED_SERVICES" ]; then
            echo "No changes detected, skipping build."
            exit 0
          fi
          for service in $CHANGED_SERVICES; do
            echo "Building $service"
            mvn -B test --file ./gpao-tex-core/$service/pom.xml
            mvn clean package -DskipTests --file ./gpao-tex-core/$service/pom.xml
          done

      - name: Log in to Docker Hub
        if: env.CHANGED_SERVICES != ''
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker images
        if: env.CHANGED_SERVICES != ''
        run: |
          for service in $CHANGED_SERVICES; do
            docker build -t ${{ secrets.DOCKER_USERNAME }}/gpro-$service-service:latest ./gpao-tex-core/$service
          done

      - name: Push Docker images
        if: env.CHANGED_SERVICES != ''
        run: |
          for service in $CHANGED_SERVICES; do
     
