name: Build & Deploy Microservices App

on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    name: Build & Deploy Spring boot Microservice App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17


      - name: Test & Build Config Service
        run: |
          mvn -B test --file pom.xml 
          mvn clean package -DskipTests
        working-directory: ./gpao-tex-core/config-server

      - name: Test & Build Discovery Service
        run: |
          mvn -B test --file pom.xml
          mvn clean package -DskipTests
        working-directory: ./gpao-tex-core/discovery

      - name: Test & Build Gateway Service
        run: |
          mvn clean package -DskipTests
        working-directory: ./gpao-tex-core/gateway

      - name: Test & Build Ordre Service
        run: |
          mvn -B test --file pom.xml
          mvn clean package -DskipTests
        working-directory: ./gpao-tex-core/ordre

      - name: Test & Build Partie Prenant Service
        run: |
          mvn -B test --file pom.xml
          mvn clean package -DskipTests
        working-directory: ./gpao-tex-core/partie-prenante

      - name: Test & Build Produit Service
        run: |
          mvn -B test --file pom.xml 
          mvn clean package -DskipTests
        working-directory: ./gpao-tex-core/produit

      - name: Test & Build Production Service
        run: |
          mvn -B test --file pom.xml
          mvn clean package -DskipTests
        working-directory: ./gpao-tex-core/production

      # Docker login step (if necessary for private repositories)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build Docker images for each service
      - name: Build Docker Image for Config Service
        uses: docker/build-push-action@v2
        with:
          context: ./gpao-tex-core/config-server
          file: ./gpao-tex-core/config-server/Dockerfile
          push: false
          tags: your-dockerhub-username/gpro-config-service:latest

      # Push Docker Image to Docker Hub
      - name: Push Docker Image for Config Service to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./gpao-tex-core/config-server
          file: ./gpao-tex-core/config-server/Dockerfile
          push: true
          tags: your-dockerhub-username/gpro-config-service:latest